// Code generated by DSL Compiler and manually enhanced. See dsl/keysight_n9.dsl.
// Dialect: Keysight_N9

package dialect

import (
	"time"

	"github.com/qooqle/mup-ribgen/pkg/dslruntime"
	"github.com/qooqle/mup-ribgen/pkg/ir"
	"github.com/qooqle/mup-ribgen/pkg/pfcp"
)

var rtn9 = dslruntime.RT{}

func init() {
	Register(&KeysightN9Transformer{})
}

// KeysightN9Transformer is the Dialect Transformer for "Keysight_N9".
// It processes PFCP N9-interface sessions as observed in Keysight Network Tester captures.
type KeysightN9Transformer struct{}

// Name returns the dialect name.
func (t *KeysightN9Transformer) Name() string { return "Keysight_N9" }

// EstablishmentToState maps a PFCP Session Establishment Request to a new PFCPSessionState.
// The DSL rule: pfcp.f_seid.seid -> SEID
func (t *KeysightN9Transformer) EstablishmentToState(req *pfcp.PFCPEstablishmentRequest) (*pfcp.PFCPSessionState, error) {
	state := &pfcp.PFCPSessionState{
		PDRs:         make(map[uint16]*pfcp.PDR),
		FARs:         make(map[uint32]*pfcp.FAR),
		QERs:         make(map[uint32]*pfcp.QER),
		LastModified: time.Now(),
	}

	// pfcp.f_seid.seid -> SEID
	if v := rtn9.GetField(req.Fields, "pfcp", "f_seid", "seid"); v != nil {
		state.SEID = rtn9.CoerceUint64(v)
	}

	return state, nil
}

// ModificationToState maps a PFCP Session Modification Request to a PFCPSessionStateDelta.
// The DSL rules:
//
//	pfcp.seid -> SEID
//	pfcp.create_pdr[*].pdr_id -> UpdatePDRs  (with full PDI stored in PDR.Fields)
//	pfcp.create_far[*].far_id -> UpdateFARs  (with forwarding params stored in FAR.Fields)
func (t *KeysightN9Transformer) ModificationToState(req *pfcp.PFCPModificationRequest) (*pfcp.PFCPSessionStateDelta, error) {
	delta := &pfcp.PFCPSessionStateDelta{
		UpdatePDRs: make(map[uint16]*pfcp.PDR),
		UpdateFARs: make(map[uint32]*pfcp.FAR),
	}

	// pfcp.seid -> SEID
	if v := rtn9.GetField(req.Fields, "pfcp", "seid"); v != nil {
		delta.SEID = rtn9.CoerceUint64(v)
	}

	// pfcp.create_pdr[*].pdr_id -> UpdatePDRs
	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "create_pdr")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			pdrID := rtn9.CoerceUint16(itemFields["pdr_id"])
			if pdrID == 0 {
				continue
			}
			delta.UpdatePDRs[pdrID] = &pfcp.PDR{PDRID: pdrID, Fields: itemFields}
		}
	}

	// pfcp.create_far[*].far_id -> UpdateFARs
	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "create_far")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			farID := rtn9.CoerceUint32(itemFields["far_id"])
			if farID == 0 {
				continue
			}
			delta.UpdateFARs[farID] = &pfcp.FAR{FARID: farID, Fields: itemFields}
		}
	}

	// pfcp.create_qer[*].qer_id – QERs stored in state via the session manager merge.
	// (QERs are not in PFCPSessionStateDelta; they are added here as a FAR extension.)

	return delta, nil
}

// StateToSessionInfo converts the accumulated PFCPSessionState to SessionInformation (IR).
// Extraction rules (manual enhancement of DSL skeleton):
//
//	SEID:            state.SEID
//	UEIPAddress:     DL PDR (pdi.source_interface = Core = 1) → pdi.ue_ip_address.ipv4
//	NetworkInstance: Forwarding FAR → forwarding_parameters.network_instance
//	EndpointAddress: Forwarding FAR → forwarding_parameters.outer_header_creation.ipv4
//	TEID:            Forwarding FAR → forwarding_parameters.outer_header_creation.teid
//	QFI:             first QER's qfi_value (stored in FAR.Fields["qfi_value"] by QER merge)
func (t *KeysightN9Transformer) StateToSessionInfo(state *pfcp.PFCPSessionState) (*ir.SessionInformation, error) {
	info := &ir.SessionInformation{
		SEID:   state.SEID,
		Source: ir.Mode1PFCP,
	}

	// Extract UE IP from DL PDR (source_interface = Core = 1)
	for _, pdr := range state.PDRs {
		pdi, _ := pdr.Fields["pdi"].(map[string]interface{})
		if pdi == nil {
			continue
		}
		if rtn9.CoerceUint8(pdi["source_interface"]) != 1 {
			continue // skip UL PDRs (Access = 0)
		}
		if ueIP, _ := pdi["ue_ip_address"].(map[string]interface{}); ueIP != nil {
			if ipv4 := rtn9.CoerceString(ueIP["ipv4"]); ipv4 != "" {
				info.UEIPAddress = ipv4
			}
		}
		if ni := rtn9.CoerceString(pdi["network_instance"]); ni != "" {
			info.NetworkInstance = ni
		}
		break
	}

	// Extract N9 endpoint and TEID from the forwarding FAR.
	// FORW = bit 2 of Octet 5 (high byte) → 0x0200 in big-endian uint16
	// (3GPP TS 29.244 §8.2.26 Table 8.2.26-1).
	for _, far := range state.FARs {
		applyAction := rtn9.CoerceUint16(far.Fields["apply_action"])
		if applyAction&0x0200 == 0 {
			continue // not a forwarding FAR
		}
		fwdParams, _ := far.Fields["forwarding_parameters"].(map[string]interface{})
		if fwdParams == nil {
			continue
		}
		if ohc, _ := fwdParams["outer_header_creation"].(map[string]interface{}); ohc != nil {
			info.TEID = rtn9.CoerceUint32(ohc["teid"])
			info.EndpointAddress = rtn9.CoerceString(ohc["ipv4"])
		}
		if ni := rtn9.CoerceString(fwdParams["network_instance"]); ni != "" {
			info.NetworkInstance = ni
		}
		break
	}

	// Extract QFI from the first QER entry
	for _, qer := range state.QERs {
		info.QFI = rtn9.CoerceUint8(qer.Fields["qfi_value"])
		if info.QFI != 0 {
			break
		}
	}

	return info, nil
}
