// Code generated by DSL Compiler and manually enhanced. See dsl/keysight_n9.dsl.
// Dialect: Keysight_N9

package dialect

import (
	"sort"
	"time"

	"github.com/qooqle/mup-ribgen/pkg/dslruntime"
	"github.com/qooqle/mup-ribgen/pkg/ir"
	"github.com/qooqle/mup-ribgen/pkg/pfcp"
)

var rtn9 = dslruntime.RT{}

func init() {
	Register(&KeysightN9Transformer{})
}

// KeysightN9Transformer is the Dialect Transformer for "Keysight_N9".
// It processes PFCP N9-interface sessions as observed in Keysight Network Tester captures.
type KeysightN9Transformer struct{}

// Name returns the dialect name.
func (t *KeysightN9Transformer) Name() string { return "Keysight_N9" }

// EstablishmentToState maps a PFCP Session Establishment Request to a new PFCPSessionState.
// The DSL rule: pfcp.f_seid.seid -> SEID
func (t *KeysightN9Transformer) EstablishmentToState(req *pfcp.PFCPEstablishmentRequest) (*pfcp.PFCPSessionState, error) {
	state := &pfcp.PFCPSessionState{
		PDRs:         make(map[uint16]*pfcp.PDR),
		FARs:         make(map[uint32]*pfcp.FAR),
		QERs:         make(map[uint32]*pfcp.QER),
		LastModified: time.Now(),
	}

	// pfcp.f_seid.seid -> SEID
	if v := rtn9.GetField(req.Fields, "pfcp", "f_seid", "seid"); v != nil {
		state.SEID = rtn9.CoerceUint64(v)
	}

	return state, nil
}

// ModificationToState maps a PFCP Session Modification Request to a PFCPSessionStateDelta.
// The DSL rules:
//
//	pfcp.seid -> SEID
//	pfcp.create_pdr[*].pdr_id -> UpdatePDRs  (with full PDI stored in PDR.Fields)
//	pfcp.create_far[*].far_id -> UpdateFARs  (with forwarding params stored in FAR.Fields)
func (t *KeysightN9Transformer) ModificationToState(req *pfcp.PFCPModificationRequest) (*pfcp.PFCPSessionStateDelta, error) {
	delta := &pfcp.PFCPSessionStateDelta{
		UpdatePDRs: make(map[uint16]*pfcp.PDR),
		UpdateFARs: make(map[uint32]*pfcp.FAR),
	}

	// pfcp.seid -> SEID
	if v := rtn9.GetField(req.Fields, "pfcp", "seid"); v != nil {
		delta.SEID = rtn9.CoerceUint64(v)
	}

	// pfcp.create_pdr[*].pdr_id -> UpdatePDRs
	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "create_pdr")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			pdrID := rtn9.CoerceUint16(itemFields["pdr_id"])
			if pdrID == 0 {
				continue
			}
			delta.UpdatePDRs[pdrID] = &pfcp.PDR{PDRID: pdrID, Fields: itemFields}
		}
	}

	// pfcp.create_far[*].far_id -> UpdateFARs
	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "create_far")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			farID := rtn9.CoerceUint32(itemFields["far_id"])
			if farID == 0 {
				continue
			}
			delta.UpdateFARs[farID] = &pfcp.FAR{FARID: farID, Fields: itemFields}
		}
	}

	// pfcp.update_far[*].far_id -> UpdateFARs
	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "update_far")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			farID := rtn9.CoerceUint32(itemFields["far_id"])
			if farID == 0 {
				continue
			}
			delta.UpdateFARs[farID] = &pfcp.FAR{FARID: farID, Fields: itemFields}
		}
	}

	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "remove_pdr")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			pdrID := rtn9.CoerceUint16(itemFields["pdr_id"])
			if pdrID == 0 {
				continue
			}
			delta.RemovePDRs = append(delta.RemovePDRs, pdrID)
		}
	}

	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "remove_far")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			farID := rtn9.CoerceUint32(itemFields["far_id"])
			if farID == 0 {
				continue
			}
			delta.RemoveFARs = append(delta.RemoveFARs, farID)
		}
	}

	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "create_qer")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			qerID := rtn9.CoerceUint32(itemFields["qer_id"])
			if qerID == 0 {
				continue
			}
			if delta.UpdateQERs == nil {
				delta.UpdateQERs = make(map[uint32]*pfcp.QER)
			}
			delta.UpdateQERs[qerID] = &pfcp.QER{QERID: qerID, Fields: itemFields}
		}
	}

	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "update_qer")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			qerID := rtn9.CoerceUint32(itemFields["qer_id"])
			if qerID == 0 {
				continue
			}
			if delta.UpdateQERs == nil {
				delta.UpdateQERs = make(map[uint32]*pfcp.QER)
			}
			delta.UpdateQERs[qerID] = &pfcp.QER{QERID: qerID, Fields: itemFields}
		}
	}

	if arr, ok := rtn9.GetArray(rtn9.GetField(req.Fields, "pfcp", "remove_qer")); ok {
		for _, item := range arr {
			itemFields, _ := item.(map[string]interface{})
			if itemFields == nil {
				continue
			}
			qerID := rtn9.CoerceUint32(itemFields["qer_id"])
			if qerID == 0 {
				continue
			}
			delta.RemoveQERs = append(delta.RemoveQERs, qerID)
		}
	}

	return delta, nil
}

// StateToSessionInfo converts the accumulated PFCPSessionState to SessionInformation (IR).
// Extraction rules (manual enhancement of DSL skeleton):
//
//	SEID:            state.SEID
//	UEIPAddress:     DL PDR (pdi.source_interface = Core = 1) → pdi.ue_ip_address.ipv4
//	NetworkInstance: Forwarding FAR → forwarding_parameters.network_instance
//	EndpointAddress: Forwarding FAR → forwarding_parameters.outer_header_creation.ipv4
//	TEID:            Forwarding FAR → forwarding_parameters.outer_header_creation.teid
//	QFI:             first QER's qfi_value (stored in FAR.Fields["qfi_value"] by QER merge)
func (t *KeysightN9Transformer) StateToSessionInfo(state *pfcp.PFCPSessionState) (*ir.SessionInformation, error) {
	infos, err := t.StateToSessionInfos(state)
	if err != nil {
		return nil, err
	}
	if len(infos) == 0 {
		return &ir.SessionInformation{
			SEID:   state.SEID,
			Source: ir.Mode1PFCP,
		}, nil
	}
	return infos[0], nil
}

// StateToSessionInfos converts state to one SessionInformation per forwarding FAR.
// Output order is deterministic (ascending FAR ID).
func (t *KeysightN9Transformer) StateToSessionInfos(state *pfcp.PFCPSessionState) ([]*ir.SessionInformation, error) {
	base := &ir.SessionInformation{
		SEID:   state.SEID,
		Source: ir.Mode1PFCP,
	}

	var ueIP, ueNI string
	for _, pdr := range state.PDRs {
		pdi, _ := pdr.Fields["pdi"].(map[string]interface{})
		if pdi == nil || rtn9.CoerceUint8(pdi["source_interface"]) != 1 {
			continue
		}
		if ueIPMap, _ := pdi["ue_ip_address"].(map[string]interface{}); ueIPMap != nil {
			if ipv4 := rtn9.CoerceString(ueIPMap["ipv4"]); ipv4 != "" {
				ueIP = ipv4
			}
		}
		if ni := rtn9.CoerceString(pdi["network_instance"]); ni != "" {
			ueNI = ni
		}
		break
	}
	base.UEIPAddress = ueIP
	base.NetworkInstance = ueNI

	farIDs := make([]uint32, 0, len(state.FARs))
	for farID, far := range state.FARs {
		if far == nil {
			continue
		}
		applyAction := rtn9.CoerceUint16(far.Fields["apply_action"])
		if applyAction&0x0200 == 0 {
			continue
		}
		farIDs = append(farIDs, farID)
	}
	sort.Slice(farIDs, func(i, j int) bool { return farIDs[i] < farIDs[j] })

	infos := make([]*ir.SessionInformation, 0, len(farIDs))
	for _, farID := range farIDs {
		far := state.FARs[farID]
		if far == nil {
			continue
		}
		info := *base
		fwdParams, _ := far.Fields["forwarding_parameters"].(map[string]interface{})
		if fwdParams != nil {
			if ohc, _ := fwdParams["outer_header_creation"].(map[string]interface{}); ohc != nil {
				info.TEID = rtn9.CoerceUint32(ohc["teid"])
				info.EndpointAddress = rtn9.CoerceString(ohc["ipv4"])
			}
			if ni := rtn9.CoerceString(fwdParams["network_instance"]); ni != "" {
				info.NetworkInstance = ni
			}
		}
		info.QFI = qfiForFAR(state, farID)
		infos = append(infos, &info)
	}
	return infos, nil
}

func qfiForFAR(state *pfcp.PFCPSessionState, farID uint32) uint8 {
	for _, pdr := range state.PDRs {
		if pdr == nil || rtn9.CoerceUint32(pdr.Fields["far_id"]) != farID {
			continue
		}
		qerID := rtn9.CoerceUint32(pdr.Fields["qer_id"])
		if qerID == 0 {
			continue
		}
		if qer := state.QERs[qerID]; qer != nil {
			if qfi := rtn9.CoerceUint8(qer.Fields["qfi_value"]); qfi != 0 {
				return qfi
			}
		}
	}
	for _, qer := range state.QERs {
		if qer == nil {
			continue
		}
		if qfi := rtn9.CoerceUint8(qer.Fields["qfi_value"]); qfi != 0 {
			return qfi
		}
	}
	return 0
}
