// Package dialect defines the DialectTransformer interface and a global registry
// for all compiled dialect implementations.
package dialect

import (
	"fmt"
	"sync"

	"github.com/qooqle/mup-ribgen/pkg/ir"
	"github.com/qooqle/mup-ribgen/pkg/pfcp"
)

// DialectTransformer converts PFCP messages to the unified Session Information
// model. Implementations are generated by the DSL Compiler (Mode-1 only).
type DialectTransformer interface {
	// EstablishmentToState converts a PFCP Session Establishment Request to a
	// new PFCPSessionState.
	EstablishmentToState(req *pfcp.PFCPEstablishmentRequest) (*pfcp.PFCPSessionState, error)

	// ModificationToState converts a PFCP Session Modification Request to a
	// PFCPSessionStateDelta (incremental changes).
	ModificationToState(req *pfcp.PFCPModificationRequest) (*pfcp.PFCPSessionStateDelta, error)

	// StateToSessionInfo converts the current PFCPSessionState to the unified
	// SessionInformation (IR).
	StateToSessionInfo(state *pfcp.PFCPSessionState) (*ir.SessionInformation, error)

	// Name returns the dialect name as declared in the DSL file.
	Name() string
}

// --- Registry ---------------------------------------------------------------

var (
	registryMu sync.RWMutex
	registry   = map[string]DialectTransformer{}
)

// Register adds a transformer to the global registry. Typically called from an
// init() function in each generated transformer file.
func Register(t DialectTransformer) {
	registryMu.Lock()
	registry[t.Name()] = t
	registryMu.Unlock()
}

// Lookup returns the registered transformer for dialectName, or an error if not
// found.
func Lookup(dialectName string) (DialectTransformer, error) {
	registryMu.RLock()
	t, ok := registry[dialectName]
	registryMu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("dialect: transformer %q not registered", dialectName)
	}
	return t, nil
}

// Registered returns all registered dialect names.
func Registered() []string {
	registryMu.RLock()
	defer registryMu.RUnlock()
	names := make([]string, 0, len(registry))
	for n := range registry {
		names = append(names, n)
	}
	return names
}
